startlist = "" # <- Fill in the wallpaper list you want to start playing first

[""] # <- Fill in the name of your wallpaper list

dir = "" # <- Fill in the directory of your wallpaper list. Both relative and absolute paths are supported.
# Relative paths must be relative to "$HOME/.config/wow/"

# -1 is the default value, meaning manual control of wallpaper switching (next/previous).
# If set to 60(or other integer), it means automatic switching, and each wallpaper will play for 60 seconds before switching to the next.
time = -1

# order can be empty, meaning no specific order is required. In this case, wallpapers are played in the loading order.
# If order is not empty, wallpapers will be played in the sequence defined in the order list.
# (Wallpapers that are not filled in will not play even in the wallpaper list directory.)
order = []

# You can have multiple wallpaper lists
["xxx"]
dir = ""
time = -1
order = []
